---
- name: Setup Load Balancer
  hosts: ha_proxy
  become: yes
  roles: 
    - haProxy

- name: Setup NFS server
  hosts: nfs_server
  become: yes
  roles:
    - nfsServer
   
- name: Setup Nfs mount points
  hosts: app_server
  become: yes
  roles:
    - nfsClient
  vars:
    nfs_server_group: "nfs_server"

- name: Setup postgres db
  hosts: db
  become: yes
  roles:
    - postgres
  vars:
    config: "app"

- name: Setup DNS server
  hosts: dns
  become: yes
  roles:
    - { role: dnsServer, tags: ["dns"] }
  tags: ["dns"]
  
- name: "Setup kubernetes cluster : Master" 
  hosts: kube_master
  vars:
    kubernetes_role: "master"
  sudo: true
  roles:
    - docker
    - kubernetes   
  tags: [kube_master]

- name: "Setup kubernetes cluster : Node"    
  hosts: kube_workers
  vars:
    kubernetes_role: "node"
  sudo: true
  roles:
    - docker
    - kubernetes
  tags: [kube_node]
