---
- name: Setup Load Balancer
  hosts: ha_proxy
  become: yes
  roles: 
    - haProxy

- name: Setup NFS server
  hosts: nfs_server
  become: yes
  roles:
    - nfsServer

- name: Setup XLR instance
  hosts: xlr_master
  become: yes
  roles:
    - xlRelease  
