---
- name: "Remove the older packages"
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine 
    
- name: "Installing yum-utils"
  yum:
    name: yum-utils
    state: present
  
- name: "Setup the docker repository"
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  
- name: "Installing docker packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: "Start docker service"
  systemd:
    name: docker
    state: started
