# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.ssh.insert_key = false
  config.vm.boot_timeout = 800
  config.ssh.private_key_path = ["keys/vagrant_key", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "keys/vagrant_key.pub", destination: "~/.ssh/authorized_keys"

  config.vm.define "first" do |first|
    first.vm.box = "centos/7"
    first.vm.network "public_network", ip: "192.168.0.107"
    first.vm.provision "shell", inline: "First VM is up"
  end

  config.vm.define "second" do |second|
    second.vm.box = "centos/7"
    second.vm.network "public_network", ip: "192.168.0.108"
    second.vm.provision "shell", inline: "Second VM is up"
  end

  config.vm.define "third" do |third|
     third.vm.box = "centos/7"
     third.vm.network "public_network", ip: "192.168.0.109"
     third.vm.provision "shell", inline: "Third VM is up"
  end
end
